# Generated by Django 4.1.7 on 2023-03-30 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"ordering": ["rank"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="producttemplate",
            options={"ordering": ["product", "order"]},
        ),
    ]
