# Generated by Django 4.1.7 on 2023-03-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0002_alter_domain_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template", models.CharField(max_length=200, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "global"), ("per_domain", "per_domain")],
                        default="per_domain",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt1", models.TextField()),
                ("prompt2", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("order", models.IntegerField(default=100)),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["template", "order"],
            },
        ),
        migrations.RemoveField(
            model_name="producttemplate",
            name="product",
        ),
        migrations.RemoveField(
            model_name="producttemplate",
            name="token1",
        ),
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_product_domain",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="product",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductTemplate",
        ),
        migrations.AddField(
            model_name="templateitem",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ranker.template"
            ),
        ),
        migrations.AddField(
            model_name="templateitem",
            name="token1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ranker.tokentype",
            ),
        ),
        # migrations.AddField(
        #     model_name="conversation",
        #     name="template",
        #     field=models.ForeignKey(
        #         default=1,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="ranker.template",
        #     ),
        #     preserve_default=False,
        # ),
        # migrations.AddConstraint(
        #     model_name="conversation",
        #     constraint=models.UniqueConstraint(
        #         fields=("template", "domain"),
        #         include=("answered_at",),
        #         name="unique_template_domain",
        #     ),
        # ),
    ]
