# Generated by Django 4.1.7 on 2023-03-31 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "ranker",
            "0003_template_templateitem_remove_producttemplate_product_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ranker.template",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("template", "domain"),
                include=("answered_at",),
                name="unique_template_domain",
            ),
        ),
    ]
