# Generated by Django 4.2.1 on 2023-05-25 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0004_alter_projectdomain_project_alter_template_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="business_json",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="business_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="naics_6",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitor_set",
                        to="ranker.domain",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_domain_set",
                        to="ranker.domain",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("brand", "brand"),
                            ("product", "product"),
                            ("competitor_brand", "competitor_brand"),
                            ("competitor_product", "competitor_product"),
                        ],
                        default="brand",
                        max_length=200,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ranker.domain"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="domain",
            name="competitors",
            field=models.ManyToManyField(
                through="ranker.Competition", to="ranker.domain"
            ),
        ),
    ]
