# Generated by Django 4.1.7 on 2023-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0004_conversation_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_model", models.CharField(max_length=200)),
                ("api_identifier", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
