# Generated by Django 4.2.1 on 2023-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0005_domain_business_json_domain_business_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="business_api_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="business_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="domain",
            name="business_retrieved_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
