# Generated by Django 4.2.1 on 2023-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0005_domain_business_json_domain_business_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="business_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
