# Generated by Django 4.1.7 on 2023-03-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0006_tokentype_alter_keywordfile_filepath_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt1", models.CharField(max_length=200)),
                ("prompt2", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(max_length=200, null=True)),
                ("order", models.IntegerField()),
                ("visible", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ranker.product"
                    ),
                ),
                (
                    "token1",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ranker.tokentype",
                    ),
                ),
            ],
        ),
    ]
