# Generated by Django 4.2.1 on 2023-06-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0006_domain_business_api_response_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="validated_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="validated_domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="validation_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("valid", "valid"),
                    ("invalid", "invalid"),
                    ("same_domain_redirect", "same_domain_redirect"),
                    ("different_domain_redirect", "different_domain_redirect"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
