# Generated by Django 4.2.1 on 2023-06-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0007_domain_validated_at_domain_validated_domain_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domain",
            old_name="validated_domain",
            new_name="validation_redirect",
        ),
        migrations.AddField(
            model_name="domain",
            name="validation_response",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="validation_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("valid", "valid"),
                    ("invalid", "invalid"),
                    ("same_domain_redirect", "same_domain_redirect"),
                    ("different_domain_redirect", "different_domain_redirect"),
                    ("validation_failed", "validation_failed"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
