# Generated by Django 4.1.7 on 2023-03-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0007_product_producttemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ranker.domain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="scope",
            field=models.CharField(
                choices=[("global", "global"), ("per_domain", "per_domain")],
                default="per_domain",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="prompt2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="token1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ranker.tokentype",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("title", models.CharField(max_length=200)),
                ("response", models.TextField(null=True)),
                ("visible", models.BooleanField(default=True)),
                ("order", models.IntegerField()),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ranker.conversation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conversation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ranker.product"
            ),
        ),
    ]
