# Generated by Django 4.2.1 on 2023-06-24 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0008_rename_validated_domain_domain_validation_redirect_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="validated_at",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="validation_code",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="validation_redirect",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="validation_response",
        ),
    ]
