# Generated by Django 4.1.7 on 2023-04-02 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ranker", "0008_rename_requests_users_project_requests_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ManyToManyField(
                through="ranker.ProjectUser", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
