# Generated by Django 4.1.7 on 2023-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0008_conversation_product_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
