# Generated by Django 4.1.7 on 2023-04-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0009_project_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="domain",
            field=models.ManyToManyField(
                through="ranker.ProjectDomain", to="ranker.domain"
            ),
        ),
    ]
