# Generated by Django 4.1.7 on 2023-04-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0010_project_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ranker.project",
            ),
        ),
    ]
