# Generated by Django 4.2.1 on 2023-06-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0011_brand_indexing_requested_at_alter_brand_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="brand",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
