# Generated by Django 4.1.7 on 2023-04-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0011_conversation_project"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="unique_template_domain",
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("template", "domain", "project", "ai_model"),
                include=("answered_at",),
                name="unique_template_domain",
            ),
        ),
    ]
