# Generated by Django 4.2.1 on 2023-06-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0012_alter_brand_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
