# Generated by Django 4.1.7 on 2023-03-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0012_conversation_requested_at_message_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="ad_cost",
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="ad_keywords",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="ad_traffic",
            field=models.BigIntegerField(null=True),
        ),
    ]
