# Generated by Django 4.1.7 on 2023-04-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0012_remove_conversation_unique_template_domain_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="formatted_response",
            new_name="markdown_response",
        ),
        migrations.AddField(
            model_name="message",
            name="json_response",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="template_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ranker.templateitem",
            ),
        ),
        migrations.AddField(
            model_name="templateitem",
            name="mode",
            field=models.CharField(
                choices=[("markdown", "markdown"), ("json", "json")],
                default="markdown",
                max_length=200,
            ),
        ),
    ]
