# Generated by Django 4.1.7 on 2023-04-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0013_rename_formatted_response_message_markdown_response_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="markdown_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="helper_text_after",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="helper_text_before",
            field=models.TextField(blank=True, null=True),
        ),
    ]
