# Generated by Django 4.1.7 on 2023-03-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0013_domain_ad_cost_domain_ad_keywords_domain_ad_traffic"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="adult_content",
            field=models.BooleanField(default=False),
        ),
    ]
