# Generated by Django 4.2.1 on 2023-06-29 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0014_newbranddomain"),
    ]

    # operations = [
    #     migrations.RenameModel(
    #         old_name="Brand",
    #         new_name="OldBrand",
    #     ),
    # ]
