# Generated by Django 4.1.7 on 2023-03-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0014_domain_adult_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="domain",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
