# Generated by Django 4.1.7 on 2023-04-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0014_alter_message_markdown_response_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=200, unique=True)),
                ("user_intent", models.TextField(null=True)),
                ("natural_language_question", models.TextField(null=True)),
                ("ai_answer", models.TextField(null=True)),
                ("likely_previous_queries", models.JSONField(null=True)),
                ("likely_next_queries", models.JSONField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="template",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ranker.project",
            ),
        ),
        migrations.CreateModel(
            name="KeywordPositions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain_text", models.CharField(max_length=200)),
                ("keyword_text", models.CharField(max_length=200)),
                ("position", models.IntegerField(null=True)),
                ("previous_position", models.IntegerField(null=True)),
                ("search_volume", models.IntegerField(null=True)),
                ("keyword_difficulty", models.IntegerField(null=True)),
                (
                    "cpc",
                    models.DecimalField(decimal_places=2, max_digits=19, null=True),
                ),
                ("url", models.URLField(null=True)),
                ("traffic", models.IntegerField(null=True)),
                (
                    "traffic_percent",
                    models.DecimalField(decimal_places=2, max_digits=19, null=True),
                ),
                (
                    "traffic_cost",
                    models.DecimalField(decimal_places=2, max_digits=19, null=True),
                ),
                (
                    "competitive_difficulty",
                    models.DecimalField(decimal_places=2, max_digits=19, null=True),
                ),
                ("results", models.BigIntegerField(null=True)),
                ("trends", models.CharField(max_length=400, null=True)),
                ("retrieved_at", models.DateTimeField(null=True)),
                ("serp", models.TextField(null=True)),
                ("intents", models.CharField(max_length=400, null=True)),
                ("type", models.CharField(max_length=400, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ranker.domain",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ranker.keyword",
                    ),
                ),
            ],
        ),
    ]
