# Generated by Django 4.2.1 on 2023-06-29 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0015_rename_brand_oldbrand"),
    ]

    # operations = [
    #     migrations.RenameModel(
    #         old_name="BrandKeyword",
    #         new_name="OldBrandKeyword",
    #     ),
    # ]
