# Generated by Django 4.1.7 on 2023-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0016_rename_keywordpositions_keywordposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="keywordfile",
            name="processed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
