# Generated by Django 4.2.1 on 2023-06-29 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0016_rename_brandkeyword_oldbrandkeyword"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewBrand",
            new_name="Brand",
        ),
    ]
