# Generated by Django 4.1.7 on 2023-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0016_alter_message_order_alter_producttemplate_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("product", "domain"),
                include=("answered_at",),
                name="unique_product_domain",
            ),
        ),
    ]
