# Generated by Django 4.1.7 on 2023-03-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0017_conversation_unique_product_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttemplate",
            name="prompt1",
            field=models.CharField(max_length=800),
        ),
    ]
