# Generated by Django 4.1.7 on 2023-04-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0017_keywordfile_processed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywordposition",
            name="domain_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="keywordposition",
            name="intents",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="keywordposition",
            name="keyword_text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="keywordposition",
            name="trends",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="keywordposition",
            name="type",
            field=models.TextField(null=True),
        ),
    ]
