# Generated by Django 4.1.7 on 2023-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0018_alter_keywordposition_domain_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keywordposition",
            name="url",
            field=models.TextField(null=True),
        ),
    ]
