# Generated by Django 4.2.1 on 2023-06-29 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0018_rename_newbranddomain_branddomain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="domain",
            field=models.ManyToManyField(
                through="ranker.BrandDomain", to="ranker.domain"
            ),
        ),
    ]
