# Generated by Django 4.1.7 on 2023-03-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0018_alter_producttemplate_prompt1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttemplate",
            name="prompt1",
            field=models.TextField(),
        ),
    ]
