# Generated by Django 4.1.7 on 2023-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0019_alter_keywordposition_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="answered_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="keyword",
            name="json_response",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="keyword",
            name="requested_at",
            field=models.DateTimeField(null=True),
        ),
    ]
