# Generated by Django 4.2.1 on 2023-06-29 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0019_brand_domain_rename_brandkeyword_oldbrandkeyword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="keyword",
            field=models.ManyToManyField(
                through="ranker.BrandKeyword", to="ranker.keyword"
            ),
        ),
    ]
