# Generated by Django 4.2.1 on 2023-06-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0020_oldbrand_brand_keyword_oldbrandkeyword_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="indexing_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="keyword_indexed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
