# Generated by Django 4.2.1 on 2023-06-29 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0021_oldbrand_brand_indexing_requested_at_and_more"),
    ]

    operations = [  
        migrations.CreateModel(
            name="BrandKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ranker.brand",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ranker.keyword"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="keyword",
            field=models.ManyToManyField(
                through="ranker.BrandKeyword", to="ranker.keyword"
            ),
        ),
    ]
