# Generated by Django 4.2.1 on 2023-07-14 13:22

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0023_aimodel_created_at_aimodel_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
