# Generated by Django 4.2.1 on 2023-07-14 13:57

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0025_searchvector_trigger"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="keyword",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="ranker_keyw_search__57655e_gin"
            ),
        ),
    ]
