# Generated by Django 4.2.1 on 2023-07-14 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0026_keyword_ranker_keyw_search__57655e_gin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={
                "ordering": ["rank"],
                "permissions": (("manage_domains", "Can run all domain functions"),),
            },
        ),
        migrations.AlterModelOptions(
            name="keyword",
            options={
                "permissions": (("manage_keywords", "Can run all keyword functions"),)
            },
        ),
    ]
