# Generated by Django 4.2.1 on 2023-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0027_alter_domain_options_alter_keyword_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                fields=["answered_at"], name="ranker_keyw_answere_fc942d_idx"
            ),
        ),
    ]
