# Generated by Django 4.2.1 on 2023-07-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0028_keyword_ranker_keyw_answere_fc942d_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="keyword",
            name="ranker_keyw_answere_fc942d_idx",
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(
                fields=["answered_at"],
                include=("requested_at",),
                name="idx_answered_requested_at",
            ),
        ),
    ]
