# Generated by Django 4.2.1 on 2023-08-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0029_remove_keyword_ranker_keyw_answere_fc942d_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200, unique=True)),
                ("value", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
