# Generated by Django 4.2.1 on 2023-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0030_statistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=250)),
                ("lastmod", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
