# Generated by Django 4.2.1 on 2023-09-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0031_sitemap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitemap",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("static", "Static urls"),
                    ("keywords", "Keyword responses (autogenerated)"),
                ],
                default="static",
                max_length=50,
                null=True,
            ),
        ),
    ]
