# Generated by Django 4.2.1 on 2023-09-18 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0032_alter_sitemap_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="competition",
            unique_together={("domain", "competitor")},
        ),
    ]
