# Generated by Django 4.2.1 on 2023-09-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0034_keyword_category_scores_keyword_primary_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="category_scores",
        ),
        migrations.AddField(
            model_name="keyword",
            name="traffic",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="primary_category",
            field=models.TextField(max_length=50, null=True),
        ),
    ]
