# Generated by Django 4.2.1 on 2023-09-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0035_remove_keyword_category_scores_keyword_traffic_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyword",
            old_name="traffic",
            new_name="search_volume",
        ),
        migrations.AddField(
            model_name="keyword",
            name="num_brands",
            field=models.IntegerField(null=True),
        ),
    ]
