# Generated by Django 4.2.1 on 2023-10-02 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0036_rename_traffic_keyword_search_volume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="primary_category",
        ),
    ]
