# Generated by Django 4.2.1 on 2023-10-03 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0038_keyword_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="json_response",
        ),
    ]
