# Generated by Django 4.2.1 on 2023-10-14 20:58

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0041_searchvector_trigger"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="ranker_answ_search__10e36d_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["answered_at"],
                include=("requested_at",),
                name="idx_answer_answered_at",
            ),
        ),
    ]
