# Generated by Django 4.2.1 on 2023-11-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ranker", "0042_answer_ranker_answ_search__10e36d_gin_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("keyword", "ai_model"), name="unique_answer_ai_model_keyword"
            ),
        ),
    ]
