# Generated by Django 4.1.7 on 2023-03-28 16:52
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        CITextExtension()
    ]