# Generated by Django 4.1.7 on 2023-03-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=200)),
                ("keywords", models.BigIntegerField(null=True)),
                ("traffic", models.BigIntegerField(null=True)),
                ("cost", models.BigIntegerField(null=True)),
                ("rank", models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Domains",
        ),
    ]
