# Generated by Django 4.1.7 on 2023-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owl", "0002_domain_delete_domains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
