# Generated by Django 4.1.7 on 2023-03-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owl", "0004_keywordfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keywordfile",
            old_name="domain_id",
            new_name="domain",
        ),
        migrations.RemoveField(
            model_name="keywordfile",
            name="filename",
        ),
        migrations.AlterField(
            model_name="keywordfile",
            name="filepath",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
