# Generated by Django 4.1.7 on 2023-03-13 15:17

from django.db import migrations, models
import django.db.models.deletion
import owl.models


class Migration(migrations.Migration):
    dependencies = [
        ("owl", "0005_rename_domain_id_keywordfile_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="keywordfile",
            name="filepath",
            field=models.FileField(upload_to=owl.models.keyword_directory_path),
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="owl.tokentype"
                    ),
                ),
            ],
        ),
    ]
