# Generated by Django 4.1.7 on 2023-03-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owl", "0010_message_formatted_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="answered_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="answered_at",
            field=models.DateTimeField(null=True),
        ),
    ]
