# Generated by Django 4.1.7 on 2023-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("owl", "0011_conversation_answered_at_message_answered_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="requested_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="requested_at",
            field=models.DateTimeField(null=True),
        ),
    ]
